title: "ByteSizedSecurity"
author: "Marc"
description: "Cybersecurity Insights & Analysis - Providing in-depth analysis on the latest security threats, vulnerabilities, and defense mechanisms."
url: "https://blog.bytesizedsecurity.show"

# Logo used by jekyll-seo-tag for JSON-LD publisher schema
logo: "/favicon-96x96.png"

# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
email: "marc@bytesizedsecurity.show"
twitter_username: "marc_david"
github_username: "mda1125"
linkedin_username: "marccdavid"
#facebook_username: username
#flickr_username: username
#instagram_username: username
#pinterest_username: username
#youtube_username: username

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################
theme: "minima"

rss: rss

kramdown:
  syntax_highlighter_opts:
    disable: true
    
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - SECURITY.md

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other
      category: "Security"
      image: "/favicon-96x96.png"
